# Site settings
title: Leiym Blog
SEOTitle: é›·ä¸€é¸£çš„åšå®¢ | Leiym Blog
header-img: img/home-bg.jpg
email: leiyiming6@gmail.com
description: "ä¸Robotä¸€èµ·æˆé•¿çš„foolish Geek | é›·ä¸€é¸£ï¼Œrobot Lover & C++Software Engineer | è¿™é‡Œæ˜¯é›·ä¸€é¸£çš„ä¸ªäººåšå®¢ï¼Œä¸ä½ ä¸€èµ·å‘ç°æ›´å¤§çš„ä¸–ç•Œã€?
keyword: "é›·ä¸€é¸? Leiymé›·ä¸€é¸? Leiym"
url: "http://Leiym.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     15671656868
zhihu_username:     æ´›æˆˆ
github_username:    Missmiaom
#twitter_username:  huxpro
facebook_username:  15671656868



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: lym
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing





# Analytics settings
# Baidu Analytics
#ba_track_id: 40f36defbf92a93a605c112dab344246
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "ä¸Robotä¸€èµ·æˆé•¿çš„foolish Geek"
sidebar-avatar: /img/leiyiming.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Friends
friends: [
    {
        title: "Coooooooooder_Y",
        href: "http://yangruihan.com/"
    },{
        title: "å¤©é•¶çš„åšå®?,
        href: "http://lingyu.wang/"
    },{
        title: "Lukeçš„è‡ªç•™åœ°",
        href: "http://hmqk1995.github.io"
    },{
        title: "Ebn's Blog",
        href: "http://ebnbin.com/"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    },{
        title: "è§£æ—»çš„åšå®?,
        href: "http://xieminis.me/"
    },{
        title: "DHong Say",
        href: "http://dhong.co"
    },{
        title: "å°¹å³°ä»¥ä¸º",
        href: "http://ingf.github.io/"
    },{
        title: "å‰ç«¯ç¥ç›¾å±€",
        href: "http://wepiaofei.github.io/blog/"
    }
]
